### PR TITLE
v3.8

### PR DESCRIPTION
**Pull request by brouillette**
- Implements concept of 'ploidy', supporting both haploid and diploid genotypes 
  - https://github.com/bento-platform/gohan/pull/43 
- Restructuring elasticsearch indexing strategy 
  - https://github.com/bento-platform/gohan/pull/45

### CODE REVIEW

**Review by v-rocheleau — CHANGES_REQUESTED** [review]
Looking good, will do some testing with your ticket instructions and get back

**Review by v-rocheleau — APPROVED** [review]
Lgtm, but I dont know gohan very well yet

**Review by davidlougheed — APPROVED** [review]
lgtm

**Comment by brouillette** [comment]
Thank you!

**Pull request merged**
